package br.com.samuelmarvila.ajornadadabiblia;

/** Continuação dos devocionais revisados de Levítico. */
public final class DevotionalCatalog2 {
    private DevotionalCatalog2() {}
    public static String[] get(String book,int chapter){
        if(!book.equals("Levítico")) return null;
        switch(chapter){
            case 11:return d("Levítico 11 apresenta animais considerados puros e impuros para alimentação e estabelece distinções de pureza para Israel. O capítulo termina chamando o povo à santidade porque Deus é santo.","Essas regras pertenciam à identidade de Israel como povo da aliança e organizavam aspectos cotidianos da vida. Pureza ritual não deve ser confundida automaticamente com pecado moral; eram categorias do sistema de santidade de Levítico.","O princípio central é que a vida do povo deveria refletir sua relação com Deus. Para o cristão, o capítulo não deve ser usado simplesmente para criar uma lista moderna de alimentos proibidos, mas para lembrar que nossa fé alcança a vida cotidiana e chama à santidade.","Observe hoje uma área comum da sua rotina que você costuma separar da fé. Escolha uma atitude concreta que demonstre que seguir a Deus também envolve hábitos, escolhas e disciplina.","Senhor, ensina-me a viver uma fé que alcança toda a minha rotina. Dá-me discernimento para entender tua Palavra no contexto e sabedoria para viver em santidade hoje. Em nome de Jesus, amém.");
            case 12:return d("Levítico 12 trata do período de purificação da mulher depois do parto e apresenta as ofertas que deveriam ser levadas ao santuário.","A legislação fazia parte das regras de pureza ritual de Israel. Ela não apresenta o parto como pecado moral; trata de uma condição ritual dentro da organização do culto.","É importante não transformar uma regra ritual antiga em julgamento contra mães. O texto nos ensina primeiro a respeitar o contexto e depois a reconhecer que Deus se importava até com as etapas comuns da vida do seu povo.","Evite julgamentos rápidos baseados em textos fora de contexto. Pratique hoje misericórdia com alguém que esteja vivendo uma fase de fragilidade ou mudança.","Senhor, livra-me de julgamentos apressados. Dá-me sensibilidade para compreender tua Palavra e misericórdia para tratar as pessoas com graça e respeito. Em nome de Jesus, amém.");
            case 13:return d("Levítico 13 apresenta critérios para examinar doenças ou alterações na pele e também sinais em roupas. O sacerdote avaliava a situação e determinava a condição ritual da pessoa.","O capítulo está ligado à pureza comunitária e ao cuidado com possíveis condições contagiosas dentro do acampamento. O sacerdote atuava como responsável pelo diagnóstico ritual, não como médico moderno nos termos atuais.","A passagem mostra que santidade também tinha dimensão comunitária. A vida diante de Deus não era apenas individual; havia cuidado com a comunidade e responsabilidade diante de situações que poderiam afetar outras pessoas.","Pense em uma responsabilidade que você tem com a saúde, segurança ou bem-estar de outras pessoas. Tome hoje uma atitude preventiva em vez de esperar o problema crescer.","Deus, dá-me responsabilidade e cuidado com as pessoas ao meu redor. Ensina-me a levar a sério aquilo que pode prejudicar outros e a agir com sabedoria. Em nome de Jesus, amém.");
            case 14:return d("Levítico 14 continua o tema das doenças de pele, agora tratando do processo de reintegração da pessoa considerada curada. Também apresenta regras relacionadas a manchas em casas.","O ritual de restauração envolvia sacerdote, ofertas, banho, roupas e espera. A pessoa não era simplesmente declarada apta sem um processo; havia uma reintegração cuidadosa à comunidade.","O capítulo lembra que restauração importa. Uma comunidade saudável não deve apenas afastar alguém quando existe um problema, mas também saber reconhecer, acompanhar e reintegrar quando a situação é resolvida.","Pense em alguém que precisa de uma segunda chance. Se for seguro e correto, dê um passo de reconciliação, acolhimento ou encorajamento.","Senhor, faz de mim alguém que não apenas aponta problemas, mas também participa da restauração. Dá-me sabedoria, misericórdia e equilíbrio para acolher pessoas. Em nome de Jesus, amém.");
            case 15:return d("Levítico 15 apresenta regras sobre fluxos corporais e estabelece procedimentos de limpeza e purificação. O capítulo mostra como essas situações afetavam a participação ritual na comunidade.","Essas regras pertencem ao sistema de pureza de Israel. Elas tratam de condições corporais normais ou anormais sem afirmar que toda condição física seja resultado de pecado pessoal.","A leitura cuidadosa impede dois erros: desprezar o texto como irrelevante ou transformar regras rituais em acusações contra pessoas. O capítulo nos chama a reconhecer que Deus tratava de forma organizada até situações delicadas da vida comunitária.","Tenha hoje respeito por alguém que esteja enfrentando uma situação física ou emocional constrangedora. Evite piadas e julgamentos; pratique discrição e cuidado.","Senhor, ensina-me a tratar situações delicadas com respeito. Que minha fé produza cuidado, discrição e compaixão, e não vergonha ou desprezo. Em nome de Jesus, amém.");
            case 16:return d("Levítico 16 descreve o Dia da Expiação, quando o sumo sacerdote entrava no lugar santíssimo seguindo instruções específicas para tratar a impureza e os pecados do povo.","Era o centro do calendário ritual de Israel. O acesso ao lugar santíssimo era restrito, havia sacrifícios específicos e o rito do bode emissário simbolizava a retirada das culpas do povo.","O capítulo apresenta com força a gravidade do pecado e a necessidade de reconciliação. O Novo Testamento usa o Dia da Expiação como uma das imagens para explicar a obra sacerdotal de Cristo, mas isso deve ser feito respeitando primeiro o sentido de Levítico.","Não trate pecado como algo trivial. Separe um momento para confessar a Deus aquilo que precisa ser confessado e procure viver em paz com quem você prejudicou.","Senhor, obrigado porque tu provês caminho de reconciliação. Dá-me temor diante do pecado e gratidão pela graça. Ajuda-me a viver com coração limpo e consciência sincera diante de ti. Em nome de Jesus, amém.");
            default:return null;
        }
    }
    private static String[] d(String a,String b,String c,String d,String e){return new String[]{a,b,c,d,e};}
}
