package br.com.samuelmarvila.ajornadadabiblia;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.Shader;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public class MainActivity extends Activity {
    private static final String PREFS="jornada", CURRENT="current_reading", PLAN_VERSION="plan_version";
    private static final int CURRENT_PLAN_VERSION=2;
    private static final int BG=Color.rgb(246,247,249), NAVY=Color.rgb(12,31,52), NAVY2=Color.rgb(20,52,78), GOLD=Color.rgb(218,166,62), GREEN=Color.rgb(38,137,91), GREEN_DARK=Color.rgb(20,91,62), DARK=Color.rgb(28,39,51), MUTED=Color.rgb(103,115,127), WHITE=Color.WHITE, BORDER=Color.rgb(226,230,234), SOFT=Color.rgb(235,244,239), GOLD_SOFT=Color.rgb(250,244,225), LOCK=Color.rgb(132,143,154);
    private SharedPreferences prefs; private List<Reading> readings; private Reading current;
    private TextToSpeech tts; private Button playPause; private TextView playerStatus; private boolean speaking; private int speechPart;
    private CheckBox readCheck; private Button devotionalButton;
    private Calendar calendarCursor=Calendar.getInstance();
    private final SimpleDateFormat dateKeyFormat=new SimpleDateFormat("yyyy-MM-dd",Locale.US);
    private final SimpleDateFormat monthFormat=new SimpleDateFormat("MMMM yyyy",new Locale("pt","BR"));

    @Override public void onCreate(Bundle state){
        super.onCreate(state); getWindow().setStatusBarColor(NAVY); getWindow().setNavigationBarColor(BG);
        prefs=getSharedPreferences(PREFS,MODE_PRIVATE); readings=ReadingPlan.build(); migrateOldProgress(); current=getCurrentReading(); buildHome();
        tts=new TextToSpeech(this,status->{if(status==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("pt","BR"));tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onDone(String id){runOnUiThread(()->nextSpeechPart());}public void onError(String id){runOnUiThread(()->stopSpeech());}});}});
    }
    private void migrateOldProgress(){int version=prefs.getInt(PLAN_VERSION,0);if(version<CURRENT_PLAN_VERSION){int old=prefs.getInt(CURRENT,-1);int lev=findReadingIndex("Levítico",1,1);if(old<0)old=prefs.getBoolean("lev1",false)?lev+1:lev;else if(old==90||old==91)old=prefs.getBoolean("reading_90",false)?lev+1:lev;prefs.edit().putInt(CURRENT,old).putInt(PLAN_VERSION,CURRENT_PLAN_VERSION).apply();}else if(!prefs.contains(CURRENT))prefs.edit().putInt(CURRENT,findReadingIndex("Levítico",1,1)).apply();}
    private int findReadingIndex(String book,int chapter,int verse){for(int i=0;i<readings.size();i++){Reading r=readings.get(i);if(r.book.equals(book)&&r.chapter==chapter&&r.startVerse==verse)return i;}return 0;}
    private Reading getCurrentReading(){int i=index();if(i<0)i=0;return i<readings.size()?readings.get(i):null;}
    private int index(){return prefs.getInt(CURRENT,findReadingIndex("Levítico",1,1));}
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}

    private TextView text(String s,float size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(DARK);t.setIncludeFontPadding(false);t.setPadding(0,dp(3),0,dp(3));if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private GradientDrawable outline(int color,int stroke,int strokeColor,int radius){GradientDrawable d=bg(color,radius);d.setStroke(dp(stroke),strokeColor);return d;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(50));b.setPadding(dp(14),dp(8),dp(14),dp(8));b.setStateListAnimator(null);b.setIncludeFontPadding(false);return b;}
    private Button primary(String s){Button b=button(s);b.setTextColor(WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(GREEN,17));b.setElevation(dp(1));return b;}
    private Button secondary(String s){Button b=button(s);b.setTextColor(NAVY);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(outline(WHITE,1,BORDER,17));return b;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(17),dp(18),dp(17));c.setBackground(outline(WHITE,1,BORDER,22));c.setElevation(dp(1));return c;}
    private LinearLayout darkCard(){LinearLayout c=card();c.setBackground(bg(NAVY,25));c.setElevation(dp(2));return c;}
    private void base(LinearLayout root){root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(8),dp(12),0);root.setBackgroundColor(BG);}
    private ScrollView scroll(LinearLayout content){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setClipToPadding(false);s.setPadding(0,0,0,dp(8));s.addView(content);return s;}
    private LinearLayout.LayoutParams fullWrap(){return new LinearLayout.LayoutParams(-1,-2);}
    private LinearLayout.LayoutParams gap(int bottom){LinearLayout.LayoutParams lp=fullWrap();lp.setMargins(0,0,0,dp(bottom));return lp;}
    private void SpaceView(LinearLayout p,int h){p.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}

    private void topTitle(LinearLayout root,String title,String subtitle){
        LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(5),dp(6),dp(5),dp(4));
        TextView brand=text("A JORNADA DA BÍBLIA",10.5f,true);brand.setTextColor(GOLD);h.addView(brand);
        TextView t=text(title,28,true);t.setTextColor(NAVY);h.addView(t);
        TextView sub=text(subtitle,14,false);sub.setTextColor(MUTED);sub.setPadding(0,dp(4),0,dp(2));h.addView(sub);root.addView(h);
    }

    private void addBottomNav(LinearLayout root,String selected){
        LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(3),dp(5),dp(3),dp(6));nav.setBackground(outline(WHITE,1,BORDER,22));
        String[] labels={"⌂\nInício","▣\nLeitura","♥\nDevocional","◷\nJornada","☰\nMais"};String[] keys={"home","reading","devotional","journey","more"};
        for(int i=0;i<labels.length;i++){TextView item=text(labels[i],12,true);item.setGravity(Gravity.CENTER);item.setLineSpacing(.82f,1f);item.setTextColor(keys[i].equals(selected)?GOLD:MUTED);final String key=keys[i];item.setOnClickListener(v->{if(key.equals("home"))buildHome();else if(key.equals("reading"))buildReading();else if(key.equals("devotional"))buildDevotionalHub();else if(key.equals("journey"))buildJourney();else Toast.makeText(this,"Mais opções em breve.",Toast.LENGTH_SHORT).show();});nav.addView(item,new LinearLayout.LayoutParams(0,dp(58),1));}
        LinearLayout.LayoutParams lp=fullWrap();lp.setMargins(0,dp(6),0,dp(8));root.addView(nav,lp);
    }

    private HeroArt heroArt(){return new HeroArt(this);}

    private void addHeroBrand(LinearLayout parent,String eyebrow,String title,String subtitle){
        LinearLayout hero=darkCard();hero.setPadding(dp(18),dp(17),dp(18),dp(17));TextView e=text(eyebrow,10.5f,true);e.setTextColor(Color.rgb(221,195,130));hero.addView(e);TextView t=text(title,26,true);t.setTextColor(WHITE);t.setPadding(0,dp(4),0,dp(3));hero.addView(t);TextView s=text(subtitle,14,false);s.setTextColor(Color.rgb(218,228,236));s.setLineSpacing(1.05f,1f);hero.addView(s);hero.addView(heroArt(),new LinearLayout.LayoutParams(-1,dp(92)));parent.addView(hero);
    }

    private void buildHome(){
        stopSpeech();LinearLayout root=new LinearLayout(this);base(root);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(2),dp(2),dp(2),dp(10));
        if(current==null){topTitle(root,"Sua jornada","Uma etapa por vez, do Gênesis ao Apocalipse.");LinearLayout done=card();done.setBackground(bg(SOFT,24));done.addView(text("JORNADA CONCLUÍDA",11,true));done.addView(text("Você chegou ao fim.",28,true));done.addView(text("Toda a sequência bíblica foi concluída.",15,false));content.addView(done);root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"home");setContentView(root);return;}
        int i=index();int percent=Math.round(i*100f/readings.size());
        LinearLayout hero=darkCard();hero.setPadding(dp(18),dp(15),dp(18),dp(15));TextView brand=text("A JORNADA DA BÍBLIA",11,true);brand.setTextColor(GOLD);hero.addView(brand);TextView hello=text("Bom dia, Samuel!",25,true);hello.setTextColor(WHITE);hello.setPadding(0,dp(4),0,dp(1));hero.addView(hello);TextView sub=text("Mais um passo na sua jornada com Deus.",14,false);sub.setTextColor(Color.rgb(220,229,237));hero.addView(sub);hero.addView(heroArt(),new LinearLayout.LayoutParams(-1,dp(105)));TextView ref=text(current.reference(),18,true);ref.setTextColor(WHITE);hero.addView(ref);TextView scope=text(current.scope(),13,false);scope.setTextColor(Color.rgb(207,222,232));hero.addView(scope);SpaceView(hero,8);LinearLayout pr=new LinearLayout(this);TextView st=text("Etapa "+(i+1)+" de "+readings.size(),12,true);st.setTextColor(WHITE);pr.addView(st,new LinearLayout.LayoutParams(0,-2,1));TextView pct=text(percent+"%",12,true);pct.setTextColor(GOLD);pr.addView(pct);hero.addView(pr);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(readings.size());bar.setProgress(i);hero.addView(bar,new LinearLayout.LayoutParams(-1,dp(6)));content.addView(hero,gap(12));
        LinearLayout phrase=card();phrase.setBackground(bg(GOLD_SOFT,22));TextView label=text("☀  FRASE DO DIA",10.5f,true);label.setTextColor(GREEN_DARK);phrase.addView(label);TextView ph=text("“"+phraseOfDay(current)+"”",18,true);ph.setLineSpacing(1.05f,1f);ph.setPadding(0,dp(7),0,dp(4));phrase.addView(ph);TextView refPhrase=text(current.reference(),12,false);refPhrase.setTextColor(MUTED);phrase.addView(refPhrase);LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);Button image=secondary("▧");image.setTextSize(18);image.setContentDescription("Criar imagem da frase");image.setOnClickListener(v->createAndSharePhrase(false));actions.addView(image,new LinearLayout.LayoutParams(dp(48),dp(44)));Button share=secondary("↗");share.setTextSize(19);share.setContentDescription("Compartilhar frase");share.setOnClickListener(v->createAndSharePhrase(true));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(48),dp(44));sp.setMargins(dp(7),0,0,0);actions.addView(share,sp);phrase.addView(actions);content.addView(phrase,gap(12));
        TextView section=text("CONTINUE SUA JORNADA",11,true);section.setTextColor(NAVY);section.setPadding(dp(3),0,0,dp(7));content.addView(section);Button dev=primary("♥   Devocional");dev.setTextSize(16);dev.setOnClickListener(v->buildDevotionalHub());content.addView(dev,gap(9));Button journey=secondary("◷   Minha Jornada");journey.setTextSize(16);journey.setOnClickListener(v->buildJourney());content.addView(journey,gap(4));
        root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"home");setContentView(root);
    }

    private void addStatsRow(LinearLayout content){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER);String[] values={String.valueOf(index()),String.valueOf(registeredDays()),String.valueOf(streak())};String[] labels={"etapas","dias lidos","sequência"};for(int i=0;i<3;i++){LinearLayout c=card();c.setPadding(dp(5),dp(9),dp(5),dp(9));TextView v=text(values[i],20,true);v.setGravity(Gravity.CENTER);v.setTextColor(GREEN);c.addView(v);TextView l=text(labels[i],9.5f,false);l.setGravity(Gravity.CENTER);l.setTextColor(MUTED);c.addView(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(i==0?0:dp(3),0,i==2?0:dp(3),0);row.addView(c,lp);}content.addView(row,gap(12));}
    private String phraseOfDay(Reading r){String b=r.book;if(b.equals("Levítico"))return "Aproxime-se de Deus com reverência e um coração inteiro.";if(b.equals("Gênesis"))return "Deus está presente e age mesmo quando a história ainda parece estar começando.";if(b.equals("Êxodo"))return "Deus liberta, conduz e ensina seu povo a caminhar com Ele.";if(b.equals("Números")||b.equals("Deuteronômio"))return "Fidelidade a Deus também se aprende no caminho.";if(b.equals("Salmos")||b.equals("Provérbios"))return "A Palavra de Deus merece entrar não apenas na mente, mas também na vida.";if(b.equals("Mateus")||b.equals("Marcos")||b.equals("Lucas")||b.equals("João"))return "Conhecer Jesus transforma a maneira de viver, servir e confiar.";if(b.equals("Atos"))return "O evangelho continua avançando quando pessoas comuns obedecem a Deus.";return "Leia com atenção, reflita com sinceridade e coloque em prática o que Deus está ensinando.";}

    private void buildReading(){
        stopSpeech();LinearLayout root=new LinearLayout(this);base(root);topTitle(root,"Leitura do dia","Primeiro leia a Bíblia. Depois, siga para o devocional.");LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(2),dp(12),dp(2),dp(10));
        if(current==null){content.addView(text("Sua jornada bíblica foi concluída.",20,true));root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"reading");setContentView(root);return;}
        LinearLayout c=card();c.setBackground(bg(NAVY,24));TextView e=text("ETAPA "+(index()+1)+" DE "+readings.size(),10.5f,true);e.setTextColor(GOLD);c.addView(e);TextView r=text(current.reference(),28,true);r.setTextColor(WHITE);r.setPadding(0,dp(6),0,dp(3));c.addView(r);TextView scope=text(current.scope(),14,false);scope.setTextColor(Color.rgb(217,227,235));c.addView(scope);TextView d=text(current.description,15,false);d.setTextColor(Color.rgb(232,237,241));d.setLineSpacing(1.05f,1f);d.setPadding(0,dp(8),0,dp(3));c.addView(d);c.addView(heroArt(),new LinearLayout.LayoutParams(-1,dp(78)));Button open=primary("📖  Abrir NTLH");open.setOnClickListener(v->{Intent in=new Intent(this,WebViewActivity.class);in.putExtra("url",current.sbbUrl());in.putExtra("title",current.reference()+" — NTLH");startActivity(in);});c.addView(open);content.addView(c,gap(12));
        LinearLayout mark=card();readCheck=new CheckBox(this);readCheck.setText("Eu li esta leitura na NTLH");readCheck.setTextSize(16);readCheck.setTextColor(DARK);readCheck.setPadding(0,0,0,0);readCheck.setChecked(prefs.getBoolean("reading_"+index(),false));readCheck.setOnCheckedChangeListener((b,checked)->{prefs.edit().putBoolean("reading_"+index(),checked).apply();refreshReadingButtons();});mark.addView(readCheck);TextView explain=text("O devocional só fica disponível depois que esta leitura for concluída.",13.5f,false);explain.setTextColor(MUTED);explain.setPadding(0,dp(7),0,0);mark.addView(explain);content.addView(mark,gap(12));
        devotionalButton=primary("♥  Abrir devocional");devotionalButton.setOnClickListener(v->buildDevotional());content.addView(devotionalButton,gap(10));Button back=secondary("Voltar ao início");back.setOnClickListener(v->buildHome());content.addView(back);root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"reading");setContentView(root);refreshReadingButtons();
    }
    private void refreshReadingButtons(){if(devotionalButton==null)return;boolean enabled=readCheck!=null&&readCheck.isChecked();devotionalButton.setEnabled(enabled);devotionalButton.setAlpha(enabled?1f:.42f);}

    private void buildDevotionalHub(){
        stopSpeech();LinearLayout root=new LinearLayout(this);base(root);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(2),dp(2),dp(2),dp(10));
        if(current==null){topTitle(root,"Devocional","Você concluiu toda a jornada.");content.addView(text("Toda a jornada foi concluída.",21,true));root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"devotional");setContentView(root);return;}
        boolean readDone=prefs.getBoolean("reading_"+index(),false);boolean devDone=prefs.getBoolean("devotional_"+index(),false);
        LinearLayout hero=darkCard();hero.setPadding(dp(18),dp(16),dp(18),dp(14));TextView brand=text("SEU MOMENTO COM DEUS",10.5f,true);brand.setTextColor(GOLD);hero.addView(brand);TextView title=text("Devocional",27,true);title.setTextColor(WHITE);title.setPadding(0,dp(4),0,dp(1));hero.addView(title);TextView sub=text(current.reference(),14,false);sub.setTextColor(Color.rgb(218,228,236));hero.addView(sub);hero.addView(heroArt(),new LinearLayout.LayoutParams(-1,dp(94)));content.addView(hero,gap(12));
        LinearLayout readCard=card();TextView n1=text("01",11,true);n1.setTextColor(GOLD);readCard.addView(n1);TextView rt=text("Leitura do dia",20,true);rt.setTextColor(NAVY);readCard.addView(rt);readCard.addView(text(readDone?"Leitura concluída. Você pode seguir para o segundo momento.":"Comece por aqui. Leia a passagem bíblica da etapa.",14,false));SpaceView(readCard,7);Button rb=primary(readDone?"📖  Revisar leitura":"📖  Ler a leitura do dia");rb.setOnClickListener(v->buildReading());readCard.addView(rb);content.addView(readCard,gap(10));
        LinearLayout devCard=card();devCard.setBackground(readDone?outline(WHITE,1,BORDER,22):outline(Color.rgb(244,245,246),1,BORDER,22));TextView n2=text("02",11,true);n2.setTextColor(readDone?GOLD:LOCK);devCard.addView(n2);TextView dt=text("Devocional",20,true);dt.setTextColor(readDone?NAVY:LOCK);devCard.addView(dt);devCard.addView(text(devDone?"Esta etapa já foi concluída.":readDone?"Agora é hora de contexto, reflexão, aplicação, prática e oração.":"Disponível após concluir a leitura.",14,false));SpaceView(devCard,7);Button db=primary(devDone?"✓  Devocional concluído":readDone?"♥  Ver devocional":"🔒  Primeiro faça a leitura");db.setEnabled(readDone||devDone);db.setAlpha((readDone||devDone)?1f:.45f);db.setOnClickListener(v->buildDevotional());devCard.addView(db);content.addView(devCard,gap(10));
        LinearLayout rule=card();rule.setBackground(bg(GOLD_SOFT,20));rule.addView(text("COMO FUNCIONA",10.5f,true));rule.addView(text("1  Leia a Bíblia\n2  Leia o devocional\n3  Conclua os dois\n4  A próxima etapa é liberada",14,false));content.addView(rule);root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"devotional");setContentView(root);
    }

    private void buildDevotional(){
        stopSpeech();if(!prefs.getBoolean("reading_"+index(),false)){buildDevotionalHub();return;}LinearLayout root=new LinearLayout(this);base(root);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(2),dp(2),dp(2),dp(10));
        LinearLayout hero=darkCard();hero.setPadding(dp(18),dp(15),dp(18),dp(14));TextView e=text("DEVOCIONAL",10.5f,true);e.setTextColor(GOLD);hero.addView(e);TextView title=text(current.reference(),26,true);title.setTextColor(WHITE);title.setPadding(0,dp(4),0,dp(1));hero.addView(title);TextView sub=text("Pare, reflita e deixe a Palavra falar com você.",14,false);sub.setTextColor(Color.rgb(218,228,236));hero.addView(sub);hero.addView(heroArt(),new LinearLayout.LayoutParams(-1,dp(92)));content.addView(hero,gap(12));
        String[] heads={"1  ·  Explicação do texto","2  ·  Contexto — tempo e cultura","3  ·  Aplicação — reflexão","4  ·  Prática — como viver hoje","5  ·  Oração"};
        for(int n=0;n<current.devotional.length;n++){LinearLayout c=card();TextView h=text(heads[n],16.5f,true);h.setTextColor(n==4?GREEN_DARK:NAVY);c.addView(h);TextView body=text(current.devotional[n],15.5f,false);body.setTextColor(DARK);body.setLineSpacing(1.08f,1f);body.setPadding(0,dp(7),0,dp(2));c.addView(body);content.addView(c,gap(10));}
        LinearLayout player=card();player.setBackground(bg(SOFT,20));player.addView(text("Ouvir devocional",17,true));playerStatus=text("Pronto para ouvir",13.5f,false);playerStatus.setTextColor(MUTED);player.addView(playerStatus);SpaceView(player,5);LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER_VERTICAL);playPause=primary("▶  Ouvir");playPause.setOnClickListener(v->toggleSpeech());controls.addView(playPause,new LinearLayout.LayoutParams(0,dp(52),1));Button stop=secondary("Parar");stop.setOnClickListener(v->stopSpeech());LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(92),dp(52));sp.setMargins(dp(8),0,0,0);controls.addView(stop,sp);player.addView(controls);content.addView(player,gap(12));
        Button finish=primary("✓  Concluir devocional e avançar");finish.setOnClickListener(v->completeReading());content.addView(finish,gap(10));Button back=secondary("Voltar para as duas opções");back.setOnClickListener(v->buildDevotionalHub());content.addView(back);root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"devotional");setContentView(root);
    }

    private void completeReading(){stopSpeech();int old=index();String today=dateKeyFormat.format(Calendar.getInstance().getTime());int count=prefs.getInt("day_count_"+today,0)+1;prefs.edit().putBoolean("reading_"+old,true).putBoolean("devotional_"+old,true).putInt(CURRENT,old+1).putBoolean("day_"+today,true).putInt("day_count_"+today,count).apply();current=getCurrentReading();buildCompletion();}
    private void buildCompletion(){LinearLayout root=new LinearLayout(this);base(root);topTitle(root,"Concluído","Mais uma etapa registrada na sua jornada.");LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(2),dp(15),dp(2),dp(10));LinearLayout c=card();c.setBackground(bg(SOFT,24));TextView icon=text("✓",44,true);icon.setTextColor(GREEN);icon.setGravity(Gravity.CENTER);c.addView(icon);TextView title=text("Etapa concluída",24,true);title.setGravity(Gravity.CENTER);c.addView(title);TextView msg=text("Leitura e devocional registrados. A próxima etapa agora está liberada.",14.5f,false);msg.setGravity(Gravity.CENTER);msg.setTextColor(MUTED);c.addView(msg);content.addView(c,gap(14));if(current!=null){Button next=primary("Próxima etapa  →");next.setOnClickListener(v->buildDevotionalHub());content.addView(next,gap(10));}Button journey=secondary("◷  Minha jornada");journey.setOnClickListener(v->buildJourney());content.addView(journey,gap(10));Button home=secondary("Voltar ao início");home.setOnClickListener(v->buildHome());content.addView(home);root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"home");setContentView(root);}

    private void buildJourney(){stopSpeech();LinearLayout root=new LinearLayout(this);base(root);topTitle(root,"Minha jornada","Seu ritmo de leitura, seus dias e seu calendário.");LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(2),dp(12),dp(2),dp(10));LinearLayout overview=darkCard();overview.addView(text("SEU PROGRESSO",10.5f,true));TextView p=text(Math.round(index()*100f/readings.size())+"%",31,true);p.setTextColor(WHITE);overview.addView(p);TextView done=text(index()+" etapas concluídas de "+readings.size(),14,false);done.setTextColor(Color.rgb(218,228,236));overview.addView(done);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(readings.size());bar.setProgress(index());overview.addView(bar,new LinearLayout.LayoutParams(-1,dp(6)));content.addView(overview,gap(12));addStatsRow(content);LinearLayout cal=card();TextView calTitle=text("Calendário de leitura",19,true);cal.addView(calTitle);TextView calHint=text("Cada dia aparece quando pelo menos uma etapa é concluída.",12.5f,false);calHint.setTextColor(MUTED);calHint.setPadding(0,dp(5),0,dp(2));cal.addView(calHint);SpaceView(cal,8);LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);Button prev=secondary("‹");prev.setTextSize(25);prev.setPadding(0,0,0,0);prev.setOnClickListener(v->{calendarCursor.add(Calendar.MONTH,-1);renderCalendar(cal);});nav.addView(prev,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView month=text(monthFormat.format(calendarCursor.getTime()),17,true);month.setGravity(Gravity.CENTER);month.setTextColor(NAVY);nav.addView(month,new LinearLayout.LayoutParams(0,dp(48),1));Button next=secondary("›");next.setTextSize(25);next.setPadding(0,0,0,0);next.setOnClickListener(v->{calendarCursor.add(Calendar.MONTH,1);renderCalendar(cal);});nav.addView(next,new LinearLayout.LayoutParams(dp(48),dp(48)));cal.addView(nav);renderCalendar(cal);content.addView(cal);root.addView(scroll(content),new LinearLayout.LayoutParams(-1,0,1));addBottomNav(root,"journey");setContentView(root);}
    private void renderCalendar(LinearLayout cal){TextView month=null;LinearLayout grid=null;for(int i=0;i<cal.getChildCount();i++){View v=cal.getChildAt(i);if(v instanceof LinearLayout){LinearLayout l=(LinearLayout)v;if("calendar_grid".equals(l.getTag()))grid=l;else if(l.getChildCount()==3&&l.getChildAt(1) instanceof TextView)month=(TextView)l.getChildAt(1);}}if(grid==null){grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);grid.setTag("calendar_grid");cal.addView(grid,fullWrap());}if(month!=null)month.setText(monthFormat.format(calendarCursor.getTime()));renderCalendarInto(grid);}
    private void renderCalendarInto(LinearLayout grid){grid.removeAllViews();String[] names={"D","S","T","Q","Q","S","S"};LinearLayout headerRow=new LinearLayout(this);headerRow.setOrientation(LinearLayout.HORIZONTAL);for(String n:names){TextView d=text(n,11,true);d.setGravity(Gravity.CENTER);d.setTextColor(MUTED);headerRow.addView(d,new LinearLayout.LayoutParams(0,dp(26),1));}grid.addView(headerRow);Calendar first=(Calendar)calendarCursor.clone();first.set(Calendar.DAY_OF_MONTH,1);int offset=first.get(Calendar.DAY_OF_WEEK)-1;int max=first.getActualMaximum(Calendar.DAY_OF_MONTH);Set<String> done=completedDates();String today=dateKeyFormat.format(Calendar.getInstance().getTime());LinearLayout row=null;int col=0;for(int i=0;i<offset;i++){if(col==0){row=calendarRow();grid.addView(row);}addDayCell(row,"",false,false,0);col++;}for(int day=1;day<=max;day++){if(col==0){row=calendarRow();grid.addView(row);}Calendar c=(Calendar)calendarCursor.clone();c.set(Calendar.DAY_OF_MONTH,day);String key=dateKeyFormat.format(c.getTime());boolean isDone=done.contains(key);boolean isToday=key.equals(today);addDayCell(row,String.valueOf(day),isDone,isToday,prefs.getInt("day_count_"+key,0));col++;if(col==7)col=0;}if(col>0)while(col<7){addDayCell(row,"",false,false,0);col++;}}
    private LinearLayout calendarRow(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    private void addDayCell(LinearLayout row,String label,boolean done,boolean today,int count){TextView d=text(label,13.5f,done||today);d.setGravity(Gravity.CENTER);d.setTextColor(done?GREEN:(today?DARK:MUTED));d.setBackground(done?bg(Color.rgb(213,239,224),20):today?outline(WHITE,1,GOLD,20):bg(Color.TRANSPARENT,20));d.setContentDescription(label.isEmpty()?"":label+" — "+(done?(count>1?count+" etapas concluídas":"Dia concluído"):"Sem conclusão"));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(40),1);lp.setMargins(dp(2),dp(2),dp(2),dp(2));row.addView(d,lp);}
    private Set<String> completedDates(){Set<String> out=new HashSet<>();Map<String,?> all=prefs.getAll();for(String k:all.keySet())if(k.startsWith("day_")&&k.length()>4&&!k.startsWith("day_count_"))out.add(k.substring(4));return out;}
    private int registeredDays(){return completedDates().size();}
    private int streak(){Set<String> done=completedDates();Calendar c=Calendar.getInstance();String today=dateKeyFormat.format(c.getTime());if(!done.contains(today))c.add(Calendar.DAY_OF_YEAR,-1);int n=0;while(done.contains(dateKeyFormat.format(c.getTime()))){n++;c.add(Calendar.DAY_OF_YEAR,-1);}return n;}

    private void createAndSharePhrase(boolean openShare){if(current==null)return;Bitmap bitmap=createPhraseBitmap();String uriText=MediaStore.Images.Media.insertImage(getContentResolver(),bitmap,"A Jornada da Bíblia - "+current.reference(),"Frase do dia");if(uriText==null){Toast.makeText(this,"Não foi possível criar a imagem.",Toast.LENGTH_SHORT).show();return;}Uri uri=Uri.parse(uriText);if(openShare){Intent share=new Intent(Intent.ACTION_SEND);share.setType("image/png");share.putExtra(Intent.EXTRA_STREAM,uri);share.putExtra(Intent.EXTRA_TEXT,"Frase do dia — "+current.reference());share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"Compartilhar frase"));}else Toast.makeText(this,"Imagem criada na galeria. Agora você pode compartilhar.",Toast.LENGTH_SHORT).show();}
    private Bitmap createPhraseBitmap(){int w=1080,h=1350;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setShader(new LinearGradient(0,0,w,h,NAVY,NAVY2,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.argb(45,255,255,255));c.drawCircle(850,260,190,p);p.setColor(Color.argb(35,218,166,62));c.drawCircle(850,260,260,p);p.setColor(WHITE);p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));p.setTextSize(34);c.drawText("A JORNADA DA BÍBLIA",80,110,p);p.setTextSize(26);p.setColor(Color.rgb(220,195,130));c.drawText("FRASE PARA HOJE",80,180,p);p.setColor(WHITE);p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(54);drawWrapped(c,"“"+phraseOfDay(current)+"”",80,330,920,72,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(30);p.setColor(Color.rgb(220,230,238));c.drawText(current.reference(),80,1120,p);p.setTextSize(22);p.setColor(Color.argb(210,255,255,255));c.drawText("Leia. Reflita. Viva.",80,1240,p);return b;}
    private void drawWrapped(Canvas c,String value,float x,float y,float maxWidth,float lineHeight,Paint p){String[] words=value.split(" ");String line="";float yy=y;for(String word:words){String test=line.isEmpty()?word:line+" "+word;if(p.measureText(test)>maxWidth&&!line.isEmpty()){c.drawText(line,x,yy,p);line=word;yy+=lineHeight;}else line=test;}if(!line.isEmpty())c.drawText(line,x,yy,p);}

    private void toggleSpeech(){if(tts==null)return;if(speaking){tts.stop();speaking=false;playPause.setText("▶  Continuar");playerStatus.setText("Pausado na parte "+(speechPart+1)+" de 5");}else{speaking=true;playPause.setText("Ⅱ  Pausar");speakCurrent();}}
    private void speakCurrent(){if(!speaking||current==null)return;playerStatus.setText("Reproduzindo parte "+(speechPart+1)+" de 5");tts.speak(current.devotional[speechPart],TextToSpeech.QUEUE_FLUSH,null,"devotional-"+speechPart);}
    private void nextSpeechPart(){if(!speaking)return;speechPart++;if(current!=null&&speechPart<current.devotional.length)speakCurrent();else finishSpeech();}
    private void stopSpeech(){if(tts!=null)tts.stop();speaking=false;speechPart=0;if(playPause!=null)playPause.setText("▶  Ouvir");if(playerStatus!=null)playerStatus.setText("Pronto para ouvir");}
    private void finishSpeech(){speaking=false;speechPart=0;if(playPause!=null)playPause.setText("▶  Ouvir novamente");if(playerStatus!=null)playerStatus.setText("Devocional concluído");}
    @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}

    private static class HeroArt extends View {
        private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); private final Path path=new Path();
        HeroArt(Activity c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();p.setShader(new LinearGradient(0,0,0,h,Color.rgb(28,64,92),Color.rgb(10,31,51),Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.argb(55,218,166,62));c.drawCircle(w-dp(28),dp(25),dp(30),p);p.setColor(Color.rgb(218,166,62));c.drawCircle(w-dp(28),dp(25),dp(14),p);
            p.setColor(Color.rgb(25,57,76));path.reset();path.moveTo(0,h*.63f);path.lineTo(w*.22f,h*.34f);path.lineTo(w*.42f,h*.66f);path.lineTo(w*.64f,h*.28f);path.lineTo(w,h*.62f);path.lineTo(w,h);path.lineTo(0,h);path.close();c.drawPath(path,p);
            p.setColor(Color.rgb(13,43,58));path.reset();path.moveTo(0,h*.76f);path.lineTo(w*.32f,h*.47f);path.lineTo(w*.54f,h*.78f);path.lineTo(w*.78f,h*.52f);path.lineTo(w,h*.76f);path.lineTo(w,h);path.lineTo(0,h);path.close();c.drawPath(path,p);
            p.setColor(Color.rgb(239,239,231));path.reset();path.moveTo(w*.37f,h*.70f);path.lineTo(w*.50f,h*.57f);path.lineTo(w*.63f,h*.70f);path.lineTo(w*.50f,h*.83f);path.close();c.drawPath(path,p);p.setColor(Color.rgb(205,205,194));path.reset();path.moveTo(w*.50f,h*.57f);path.lineTo(w*.50f,h*.83f);path.lineTo(w*.63f,h*.70f);path.close();c.drawPath(path,p);
        }
        private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    }
}