package br.com.samuelmarvila.ajornadadabiblia;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.media.AudioAttributes;import android.speech.tts.TextToSpeech;import android.speech.tts.Voice;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class ModernActivity extends Activity{
 static final int BG=Color.rgb(247,244,237),NAVY=Color.rgb(24,45,63),GOLD=Color.rgb(202,155,56),GREEN=Color.rgb(44,137,87),TEXT=Color.rgb(38,45,50),MUTED=Color.rgb(103,112,118),WHITE=Color.WHITE,CREAM=Color.rgb(255,251,241);
 SharedPreferences pref; List<Reading> plan; Reading current; int index; LinearLayout root,body; ArrayDeque<String> back=new ArrayDeque<>(); TextToSpeech tts;
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView text(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans-serif",b?1:0));v.setIncludeFontPadding(false);return v;} TextView title(String s,float z,int c){TextView v=text(s,z,c,true);v.setTypeface(Typeface.create("serif",Typeface.BOLD));return v;}
 GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} GradientDrawable stroke(int c,int line,int r){GradientDrawable g=shape(c,r);g.setStroke(dp(1),line);return g;}
 LinearLayout.LayoutParams m(int t,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(t),0,dp(b));return p;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);pref=getSharedPreferences("jornada",MODE_PRIVATE);plan=ReadingPlan.build();index=pref.getInt("current_reading",findStart());if(index<0)index=0;if(index>plan.size())index=plan.size();current=index<plan.size()?plan.get(index):null;tts=new TextToSpeech(this,s->{if(s==TextToSpeech.SUCCESS)configureVoice();});open("home",false);}
 void configureVoice(){int lang=tts.setLanguage(Locale.forLanguageTag("pt-BR"));if(lang==TextToSpeech.LANG_MISSING_DATA||lang==TextToSpeech.LANG_NOT_SUPPORTED)tts.setLanguage(new Locale("pt","BR"));tts.setSpeechRate(pref.getFloat("tts_rate",.88f));tts.setPitch(.96f);try{Set<Voice> voices=tts.getVoices();Voice best=null;for(Voice v:voices){Locale l=v.getLocale();if(!"pt".equalsIgnoreCase(l.getLanguage())||!"BR".equalsIgnoreCase(l.getCountry())||v.isNetworkConnectionRequired())continue;if(best==null||v.getQuality()>best.getQuality()||(v.getQuality()==best.getQuality()&&v.getLatency()<best.getLatency()))best=v;}if(best!=null)tts.setVoice(best);}catch(Exception ignored){}tts.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ASSISTANCE_ACCESSIBILITY).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build());}
 int findStart(){for(int i=0;i<plan.size();i++)if(plan.get(i).book.equals("Levítico")&&plan.get(i).chapter==1)return i;return 0;}
 void open(String s,boolean add){if(add&&!s.equals("home"))back.push(page);page=s;if(s.equals("home"))home();else if(s.equals("read"))reading();else if(s.equals("devhub"))devHub();else if(s.equals("dev"))devotional();else if(s.equals("journey"))journey();else if(s.equals("settings"))settings();else if(s.equals("about"))about();else if(s.equals("help"))help();else more();}
 String page="home"; @Override public void onBackPressed(){if(!back.isEmpty())open(back.pop(),false);else super.onBackPressed();}
 void base(String selected){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(18),dp(18),dp(24));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));bottom(selected);setContentView(root);}
 void bottom(String selected){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(6),dp(7),dp(6),dp(7));n.setBackground(shape(NAVY,24));String[] ids={"home","read","devhub","journey","more"};String[] labels={"Início","Leitura","Devocional","Jornada","Mais"};int[] icons={R.drawable.ic_home,R.drawable.ic_book,R.drawable.ic_pray,R.drawable.ic_journey,R.drawable.ic_more};for(int i=0;i<5;i++){final String id=ids[i];LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);ImageView iv=new ImageView(this);iv.setImageResource(icons[i]);iv.setColorFilter(id.equals(selected)?GOLD:Color.rgb(190,204,214));item.addView(iv,new LinearLayout.LayoutParams(-1,dp(25)));TextView l=text(labels[i],10,id.equals(selected)?GOLD:Color.rgb(190,204,214),id.equals(selected));l.setGravity(Gravity.CENTER);item.addView(l,m(2,0));item.setOnClickListener(v->open(id,true));n.addView(item,new LinearLayout.LayoutParams(0,dp(60),1));}root.addView(n,new LinearLayout.LayoutParams(-1,dp(72)));}
 ImageView icon(int res,int color,int size){ImageView i=new ImageView(this);i.setImageResource(res);i.setColorFilter(color);i.setPadding(dp(5),dp(5),dp(5),dp(5));i.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));return i;}
 LinearLayout card(int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(17),dp(18),dp(17));c.setBackground(stroke(color,color==WHITE?Color.rgb(226,222,214):color,20));return c;}
 Button button(String label,boolean primary,int res){Button b=new Button(this);b.setText(label);b.setTextSize(15);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(primary?WHITE:NAVY);b.setMinHeight(dp(52));b.setPadding(dp(14),0,dp(14),0);b.setBackground(shape(primary?GREEN:WHITE,16));if(res!=0){b.setCompoundDrawablesWithIntrinsicBounds(getDrawable(res),null,null,null);b.getCompoundDrawables()[0].setTint(primary?WHITE:NAVY);b.setCompoundDrawablePadding(dp(10));}return b;}
 void hero(String eyebrow,String h,String sub,int res){LinearLayout c=card(NAVY);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(icon(res,GOLD,40));TextView e=text(eyebrow,10,GOLD,true);e.setLetterSpacing(.12f);row.addView(e,marg(10));c.addView(row);c.addView(title(h,27,WHITE),m(10,4));c.addView(text(sub,14,Color.rgb(218,228,235),false));body.addView(c,m(0,14));}
 LinearLayout.LayoutParams marg(int l){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),0,0,0);return p;}
 String greeting(){Calendar now=Calendar.getInstance();int hour=now.get(Calendar.HOUR_OF_DAY);if(hour>=5&&hour<12)return "Bom dia, Samuel!";if(hour>=12&&hour<18)return "Boa tarde, Samuel!";return "Boa noite, Samuel!";}
 String dailyVerse(){String[][] verses={{"Salmo 119:105","A tua palavra é lâmpada para os meus pés e luz para o meu caminho."},{"Provérbios 3:5-6","Confie no Senhor de todo o seu coração e reconheça o Senhor em todos os seus caminhos."},{"Isaías 41:10","Não tenha medo, pois eu estou com você; não fique assustado, pois eu sou o seu Deus."},{"Mateus 6:33","Busquem primeiro o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas."},{"João 8:12","Eu sou a luz do mundo. Quem me segue terá a luz da vida."},{"Filipenses 4:13","Tudo posso naquele que me fortalece."},{"Salmo 23:1","O Senhor é o meu pastor; nada me faltará."}};Calendar now=Calendar.getInstance();int day=now.get(Calendar.DAY_OF_YEAR);return verses[(day-1)%verses.length][0]+"\n\n\""+verses[(day-1)%verses.length][1]+"\"";}
 void home(){base("home");if(current==null){body.addView(title("Jornada concluída",30,NAVY));return;}hero("A JORNADA DA BÍBLIA",greeting(),"Mais um passo na sua jornada com Deus.",R.drawable.ic_spark);LinearLayout p=card(WHITE);LinearLayout r=new LinearLayout(this);r.addView(text("Seu progresso",14,MUTED,true),new LinearLayout.LayoutParams(0,-2,1));r.addView(text((index*100/Math.max(1,plan.size()))+"%",17,GREEN,true));p.addView(r);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,plan.size()));bar.setProgress(index);p.addView(bar,m(10,0));body.addView(p,m(0,14));LinearLayout q=card(CREAM);LinearLayout qr=new LinearLayout(this);qr.addView(icon(R.drawable.ic_spark,GREEN,30));qr.addView(text("VERSÍCULO DO DIA",10,GREEN,true),marg(8));TextView verse=title(dailyVerse(),19,TEXT);verse.setLineSpacing(0,1.18f);q.addView(verse,m(10,0));body.addView(q,m(0,16));body.addView(text("SEU PRÓXIMO PASSO",10,NAVY,true),m(2,8));Button d=button("Devocional",true,R.drawable.ic_pray);d.setOnClickListener(v->open("devhub",true));body.addView(d,m(0,9));Button j=button("Minha Jornada",false,R.drawable.ic_journey);j.setOnClickListener(v->open("journey",true));body.addView(j);}
 void reading(){base("read");if(current==null)return;body.addView(text("LEITURA DO DIA",10,GREEN,true));body.addView(title("Leia a Palavra",29,NAVY),m(6,4));body.addView(text("Um capítulo de cada vez. Uma etapa de cada vez.",14,MUTED,false),m(0,14));hero("ETAPA "+(index+1)+" DE "+plan.size(),current.reference(),current.scope(),R.drawable.ic_book);LinearLayout c=card(WHITE);c.addView(text(current.description,15,TEXT,false));Button open=button("Abrir NTLH",true,R.drawable.ic_book);open.setOnClickListener(v->{Intent i=new Intent(this,WebViewActivity.class);i.putExtra("url",current.sbbUrl());i.putExtra("title",current.reference()+" — NTLH");startActivity(i);});c.addView(open,m(12,8));body.addView(c,m(0,12));LinearLayout mark=card(WHITE);CheckBox cb=new CheckBox(this);cb.setText("Eu li esta leitura na NTLH");cb.setTextSize(16);cb.setTextColor(TEXT);cb.setChecked(pref.getBoolean("reading_"+index,false));mark.addView(cb);mark.addView(text("Depois disso, o devocional fica disponível.",13,MUTED,false),m(4,0));body.addView(mark,m(0,12));}
 void devHub(){base("devhub");hero("SEU MOMENTO COM DEUS","Devocional","Primeiro a leitura. Depois, a reflexão.",R.drawable.ic_pray);boolean r=pref.getBoolean("reading_"+index,false);LinearLayout a=step("01","Leitura do dia",r?"Leitura concluída.":"Comece lendo a passagem bíblica.",r?"Revisar leitura":"Ler a leitura",r,R.drawable.ic_book,()->open("read",true));body.addView(a,m(0,0));LinearLayout b=step("02","Devocional",r?"Agora pare, reflita, pratique e ore.":"Disponível após concluir a leitura.","Abrir devocional",r,R.drawable.ic_pray,()->open("dev",true));body.addView(b,m(0,10));LinearLayout flow=card(CREAM);flow.addView(text("A ORDEM DA JORNADA",10,GREEN,true));flow.addView(text("1  Leia a Bíblia\n2  Faça o devocional\n3  Conclua a etapa\n4  A próxima etapa será liberada",14,TEXT,false),m(7,0));body.addView(flow,m(0,12));}
 LinearLayout step(String n,String h,String sub,String label,boolean enabled,int res,Runnable run){LinearLayout c=card(WHITE);LinearLayout top=new LinearLayout(this);top.addView(icon(res,GOLD,30));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(n,10,GOLD,true));tx.addView(text(h,20,NAVY,true),m(3,0));top.addView(tx,marg(8));c.addView(top);c.addView(text(sub,13,MUTED,false),m(9,9));Button b=button(label,enabled,res);b.setEnabled(enabled);b.setAlpha(enabled?1:.45f);b.setOnClickListener(v->run.run());c.addView(b);return c;}
 void devotional(){if(!pref.getBoolean("reading_"+index,false)){devHub();return;}base("devhub");hero("DEVOCIONAL",current.reference(),"Pare, reflita e deixe a Palavra falar com você.",R.drawable.ic_pray);String[] heads={"Explicação do texto","Contexto — tempo e cultura","Aplicação — reflexão","Prática — como viver hoje","Oração"};int[] ico={R.drawable.ic_book,R.drawable.ic_info,R.drawable.ic_favorite,R.drawable.ic_check,R.drawable.ic_pray};StringBuilder spoken=new StringBuilder();for(int i=0;i<5;i++){LinearLayout c=card(WHITE);LinearLayout h=new LinearLayout(this);h.addView(icon(ico[i],GOLD,30));h.addView(text((i+1)+"  ·  "+heads[i],16,NAVY,true),marg(8));c.addView(h);String s=current.devotional!=null&&i<current.devotional.length?current.devotional[i]:"Continue meditando neste texto e aplique a Palavra com fidelidade.";spoken.append(heads[i]).append(". ").append(s).append(". ");TextView t=text(s,15,TEXT,false);t.setLineSpacing(0,1.12f);c.addView(t,m(9,0));body.addView(c,m(0,i==0?0:10));}Button voice=button("Ouvir devocional",false,R.drawable.ic_volume);voice.setOnClickListener(v->speak(spoken.toString()));body.addView(voice,m(14,8));Button done=button("Concluir devocional e avançar",true,R.drawable.ic_check);done.setOnClickListener(v->complete());body.addView(done);}
 void complete(){pref.edit().putBoolean("reading_"+index,true).putBoolean("devotional_"+index,true).putBoolean("day_"+day(),true).putInt("current_reading",index+1).apply();index++;current=index<plan.size()?plan.get(index):null;back.clear();open("home",false);}
 String day(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
 void journey(){base("journey");body.addView(text("MINHA JORNADA",10,GREEN,true));body.addView(title("Seu caminho pela Bíblia",29,NAVY),m(6,4));body.addView(text("Acompanhe seu progresso sem perder o ritmo.",14,MUTED,false),m(0,14));LinearLayout p=card(NAVY);int pct=plan.size()==0?0:index*100/plan.size();p.addView(text("SEU PROGRESSO",10,GOLD,true));p.addView(title(pct+"%",34,WHITE),m(7,2));p.addView(text(index+" etapas concluídas de "+plan.size(),13,Color.rgb(215,225,234),false));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,plan.size()));bar.setProgress(index);p.addView(bar,m(10,0));body.addView(p,m(0,12));LinearLayout s=card(WHITE);s.addView(text("ETAPA ATUAL",10,GREEN,true));s.addView(text(current==null?"Jornada concluída":current.reference(),21,NAVY,true),m(6,0));body.addView(s,m(0,10));}
 void more(){base("more");body.addView(text("MAIS",10,GREEN,true));body.addView(title("Configurações e informações",28,NAVY),m(6,4));body.addView(text("Tudo o que você precisa para usar a Jornada da Bíblia.",14,MUTED,false),m(0,16));menu("Configurações",R.drawable.ic_settings,()->open("settings",true));menu("Sobre o aplicativo",R.drawable.ic_info,()->open("about",true));menu("Ajuda",R.drawable.ic_help,()->open("help",true));}
 void menu(String s,int res,Runnable r){Button b=button(s,false,res);b.setOnClickListener(v->r.run());body.addView(b,m(0,10));}
 void settings(){base("more");body.addView(text("CONFIGURAÇÕES",10,GREEN,true));body.addView(title("Preferências",29,NAVY),m(6,4));body.addView(text("Personalize a experiência de leitura e áudio.",14,MUTED,false),m(0,16));LinearLayout voice=card(WHITE);voice.addView(text("VOZ DO DEVOCIONAL",10,GREEN,true));float rate=pref.getFloat("tts_rate",.88f);voice.addView(text("Velocidade: "+rateLabel(rate),17,NAVY,true),m(6,0));voice.addView(text("Escolha uma velocidade confortável para ouvir o devocional.",13,MUTED,false),m(5,10));Button speed=button("Alterar velocidade",false,R.drawable.ic_volume);speed.setOnClickListener(v->chooseRate());voice.addView(speed);Button test=button("Testar voz",false,R.drawable.ic_volume);test.setOnClickListener(v->speak("Esta é a voz do devocional da Jornada da Bíblia."));voice.addView(test,m(8,0));body.addView(voice,m(0,12));LinearLayout reset=card(WHITE);reset.addView(text("JORNADA",10,GREEN,true));reset.addView(text("Recomeçar a jornada",17,NAVY,true),m(6,0));reset.addView(text("Apaga apenas o progresso da leitura e dos devocionais.",13,MUTED,false),m(5,10));Button rb=button("Recomeçar desde Levítico 1",false,R.drawable.ic_check);rb.setOnClickListener(v->confirmReset());reset.addView(rb);body.addView(reset,m(0,12));}
 String rateLabel(float r){if(r<.85f)return "0,8×";if(r<.94f)return "0,9×";if(r<1.05f)return "1,0×";if(r<1.15f)return "1,1×";return "1,2×";}
 void chooseRate(){String[] labels={"0,8× — mais lenta","0,9× — confortável","1,0× — normal","1,1× — mais rápida","1,2× — rápida"};final float[] rates={.80f,.88f,1.0f,1.10f,1.20f};int selected=2;float cur=pref.getFloat("tts_rate",.88f);for(int i=0;i<rates.length;i++)if(Math.abs(cur-rates[i])<.02)selected=i;new AlertDialog.Builder(this).setTitle("Velocidade da voz").setSingleChoiceItems(labels,selected,(d,w)->{pref.edit().putFloat("tts_rate",rates[w]).apply();if(tts!=null)tts.setSpeechRate(rates[w]);d.dismiss();open("settings",false);}).setNegativeButton("Cancelar",null).show();}
 void confirmReset(){new AlertDialog.Builder(this).setTitle("Recomeçar a jornada?").setMessage("Seu progresso de leitura e devocionais será apagado. A jornada voltará para Levítico 1.").setNegativeButton("Cancelar",null).setPositiveButton("Recomeçar",(d,w)->resetJourney()).show();}
 void resetJourney(){SharedPreferences.Editor e=pref.edit();for(String k:pref.getAll().keySet())if(k.startsWith("reading_")||k.startsWith("devotional_")||k.startsWith("day_"))e.remove(k);e.putInt("current_reading",findStart()).apply();index=findStart();current=plan.get(index);back.clear();open("home",false);}
 void about(){base("more");body.addView(text("SOBRE",10,GREEN,true));body.addView(title("A Jornada da Bíblia",29,NAVY),m(6,4));body.addView(text("Versão "+BuildConfig.VERSION_NAME,13,MUTED,false),m(0,4));LinearLayout c=card(WHITE);c.addView(text("PROPÓSITO",10,GREEN,true));c.addView(text("A Jornada da Bíblia foi criada para ajudar você a percorrer as Escrituras em sequência, com leitura, reflexão, prática e oração.",15,TEXT,false),m(7,0));body.addView(c,m(0,12));LinearLayout n=card(CREAM);n.addView(text("TEXTO BÍBLICO",10,GREEN,true));n.addView(text("A leitura bíblica é aberta na NTLH por meio do site da Sociedade Bíblica do Brasil. O aplicativo não incorpora o texto integral da tradução.",14,TEXT,false),m(7,0));Button sbb=button("Abrir Sociedade Bíblica do Brasil",false,R.drawable.ic_book);sbb.setOnClickListener(v->{Intent i=new Intent(this,WebViewActivity.class);i.putExtra("url","https://www.sbb.org.br/");i.putExtra("title","Sociedade Bíblica do Brasil");startActivity(i);});n.addView(sbb,m(10,0));body.addView(n,m(0,12));}
 void help(){base("more");body.addView(text("AJUDA",10,GREEN,true));body.addView(title("Como usar o aplicativo",29,NAVY),m(6,4));body.addView(text("Siga a jornada no seu ritmo, sem pular etapas.",14,MUTED,false),m(0,16));helpCard("1. Leitura do dia","Abra a leitura e toque em Abrir NTLH para ler o capítulo na Sociedade Bíblica do Brasil.");helpCard("2. Concluir a leitura","Depois de ler, marque a leitura como concluída. Isso libera o devocional da etapa atual.");helpCard("3. Devocional","Leia as cinco partes: Explicação do texto, Contexto — tempo e cultura, Aplicação — reflexão, Prática — como viver hoje e Oração.");helpCard("4. Ouvir devocional","No fim do devocional, toque em Ouvir devocional. A voz pode ser ajustada em Mais > Configurações.");helpCard("5. Avançar","Conclua o devocional para liberar a próxima etapa. Se você ficar alguns dias sem usar o app, a jornada continua de onde parou.");}
 void helpCard(String h,String s){LinearLayout c=card(WHITE);c.addView(text(h,17,NAVY,true));c.addView(text(s,14,TEXT,false),m(6,0));body.addView(c,m(0,10));}
 void speak(String s){if(tts!=null){tts.stop();Bundle p=new Bundle();p.putString(TextToSpeech.Engine.KEY_PARAM_UTTERANCE_ID,"devocional");tts.speak(s,TextToSpeech.QUEUE_FLUSH,p,"devocional");}}
 @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
