package br.com.samuelmarvila.ajornadadabiblia;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class PremiumActivity extends Activity{
 private static final int BG=Color.rgb(247,244,237),NAVY=Color.rgb(25,48,67),BLUE=Color.rgb(49,86,112),GOLD=Color.rgb(205,157,58),GREEN=Color.rgb(45,137,88),GREEN_LIGHT=Color.rgb(224,242,231),CREAM=Color.rgb(255,251,241),WHITE=Color.WHITE,TEXT=Color.rgb(38,45,50),MUTED=Color.rgb(105,113,118),LINE=Color.rgb(225,221,212);
 private SharedPreferences p;private List<Reading> rs;private Reading cur;private LinearLayout root,content;private int idx;private CheckBox read;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);p=getSharedPreferences("jornada",MODE_PRIVATE);rs=ReadingPlan.build();idx=p.getInt("current_reading",findLev());if(idx<0)idx=0;if(idx>rs.size())idx=rs.size();cur=idx<rs.size()?rs.get(idx):null;home();}
 private int findLev(){for(int i=0;i<rs.size();i++){Reading r=rs.get(i);if("Levítico".equals(r.book)&&r.chapter==1&&r.startVerse==1)return i;}return 0;}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 private TextView tv(String s,float z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setIncludeFontPadding(false);t.setTypeface(Typeface.create("sans-serif",bold?Typeface.BOLD:Typeface.NORMAL));return t;}
 private TextView serif(String s,float z,int color){TextView t=tv(s,z,color,false);t.setTypeface(Typeface.create("serif",Typeface.BOLD));return t;}
 private GradientDrawable bg(int color,int r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
 private GradientDrawable outline(int fill,int color,int r){GradientDrawable g=bg(fill,r);g.setStroke(dp(1),color);return g;}
 private LinearLayout.LayoutParams lp(int l,int t,int r,int b){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.setMargins(dp(l),dp(t),dp(r),dp(b));return x;}
 private Button button(String text,boolean primary){Button b=new Button(this);b.setText(text);b.setTextSize(15);b.setAllCaps(false);b.setMinHeight(dp(50));b.setPadding(dp(14),0,dp(14),0);b.setStateListAnimator(null);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(primary?WHITE:NAVY);b.setBackground(bg(primary?GREEN:WHITE,15));return b;}
 private LinearLayout card(int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(outline(color,color==WHITE?LINE:color,20));return c;}
 private void setup(String selected){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(18),dp(16),dp(20));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));nav(selected);setContentView(root);}
 private void nav(String selected){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(5),dp(5),dp(5),dp(6));n.setBackground(bg(NAVY,22));String[] icons={"⌂","▣","♥","◷","☰"};String[] names={"Início","Leitura","Devocional","Jornada","Mais"};String[] keys={"home","read","dev","journey","more"};for(int i=0;i<5;i++){final String k=keys[i];LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);TextView ic=tv(icons[i],21,k.equals(selected)?GOLD:Color.rgb(188,202,213),false);ic.setGravity(Gravity.CENTER);TextView tx=tv(names[i],10,k.equals(selected)?GOLD:Color.rgb(188,202,213),k.equals(selected));tx.setGravity(Gravity.CENTER);item.addView(ic,new LinearLayout.LayoutParams(-1,dp(27)));item.addView(tx,lp(0,1,0,0));item.setOnClickListener(v->{if(k.equals("home"))home();else if(k.equals("read"))reading();else if(k.equals("dev"))hub();else if(k.equals("journey"))journey();else more();});n.addView(item,new LinearLayout.LayoutParams(0,dp(61),1));}root.addView(n,new LinearLayout.LayoutParams(-1,dp(72)));}
 private void header(String eyebrow,String title,String sub){TextView e=tv(eyebrow,10,GREEN,true);e.setLetterSpacing(.12f);content.addView(e);content.addView(serif(title,29,NAVY),lp(0,6,0,4));content.addView(tv(sub,14,MUTED,false),lp(0,0,0,16));}
 private LinearLayout banner(String icon,String eyebrow,String title,String sub){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(20),dp(19),dp(20),dp(19));b.setBackground(bg(NAVY,24));LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);TextView i=tv(icon,28,GOLD,false);line.addView(i,new LinearLayout.LayoutParams(dp(42),dp(42)));TextView e=tv(eyebrow,10,GOLD,true);e.setLetterSpacing(.1f);line.addView(e,lp(10,0,0,0));b.addView(line);b.addView(serif(title,27,WHITE),lp(0,9,0,3));b.addView(tv(sub,13,Color.rgb(218,228,235),false));return b;}
 private void home(){setup("home");if(cur==null){header("JORNADA CONCLUÍDA","Parabéns!","Você completou a jornada bíblica.");return;}content.addView(banner("✦","A JORNADA DA BÍBLIA","Bom dia, Samuel!","Mais um passo na sua jornada com Deus."),lp(0,0,0,14));LinearLayout prog=card(WHITE);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(tv("Sua jornada",14,MUTED,true),new LinearLayout.LayoutParams(0,-2,1));row.addView(tv((idx*100/Math.max(1,rs.size()))+"%",17,GREEN,true));prog.addView(row);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,rs.size()));bar.setProgress(idx);prog.addView(bar,lp(0,9,0,0));content.addView(prog,lp(0,0,0,14));LinearLayout phrase=card(CREAM);phrase.addView(tv("☀  FRASE DO DIA",10,GREEN,true));phrase.addView(serif("“"+phrase()+"”",19,TEXT),lp(0,8,0,6));phrase.addView(tv(cur.reference(),12,MUTED,false));content.addView(phrase,lp(0,0,0,16));content.addView(tv("SEU PRÓXIMO PASSO",10,NAVY,true),lp(2,0,0,8));Button d=button("♥   Devocional",true);d.setOnClickListener(v->hub());content.addView(d,lp(0,0,0,9));Button j=button("◷   Minha Jornada",false);j.setOnClickListener(v->journey());content.addView(j);}
 private String phrase(){return cur.book.equals("Levítico")?"Aproxime-se de Deus com reverência e um coração inteiro.":"Leia com atenção, reflita com sinceridade e viva a Palavra.";}
 private void reading(){setup("read");header("LEITURA DO DIA","Leia a Palavra","Um capítulo de cada vez. Uma etapa de cada vez.");if(cur==null)return;content.addView(banner("▣","ETAPA "+(idx+1)+" DE "+rs.size(),cur.reference(),cur.scope()),lp(0,0,0,14));LinearLayout info=card(WHITE);info.addView(tv(cur.description,15,TEXT,false));Button open=button("▣   Abrir NTLH",true);open.setOnClickListener(v->{Intent i=new Intent(this,WebViewActivity.class);i.putExtra("url",cur.sbbUrl());i.putExtra("title",cur.reference()+" — NTLH");startActivity(i);});info.addView(open,lp(0,12,0,0));content.addView(info,lp(0,0,0,12));LinearLayout mark=card(WHITE);read=new CheckBox(this);read.setText("Eu li esta leitura na NTLH");read.setTextSize(16);read.setTextColor(TEXT);read.setChecked(p.getBoolean("reading_"+idx,false));mark.addView(read);mark.addView(tv("Depois disso, o devocional fica disponível.",13,MUTED,false),lp(0,5,0,0));content.addView(mark,lp(0,0,0,12));Button go=button("♥   Ir para o devocional",true);go.setEnabled(read.isChecked());go.setAlpha(read.isChecked()?1:.45f);read.setOnCheckedChangeListener((v,c)->{p.edit().putBoolean("reading_"+idx,c).apply();go.setEnabled(c);go.setAlpha(c?1:.45f);});go.setOnClickListener(v->hub());content.addView(go);}
 private void hub(){setup("dev");if(cur==null){header("DEVOCIONAL","Jornada concluída","Você completou todas as etapas.");return;}content.addView(banner("♥","SEU MOMENTO COM DEUS","Devocional","Primeiro a leitura. Depois, a reflexão."),lp(0,0,0,14));boolean r=p.getBoolean("reading_"+idx,false),d=p.getBoolean("devotional_"+idx,false);step("01","▣  Leitura do dia",r?"Leitura concluída.":"Comece lendo a passagem bíblica.",r?"Revisar leitura":"Ler a leitura",()->reading(),true);step("02","♥  Devocional",d?"Etapa já concluída.":r?"Agora pare, reflita, pratique e ore.":"Disponível após concluir a leitura.",d?"Ver devocional":r?"Abrir devocional":"🔒  Primeiro faça a leitura",()->dev(),r||d);LinearLayout flow=card(CREAM);flow.addView(tv("A ORDEM DA JORNADA",10,GREEN,true));flow.addView(tv("1  Leia a Bíblia\n2  Faça o devocional\n3  Conclua a etapa\n4  A próxima etapa será liberada",14,TEXT,false),lp(0,7,0,0));content.addView(flow);}
 private void step(String n,String h,String s,String label,final Runnable action,boolean enabled){LinearLayout c=card(WHITE);c.addView(tv(n,10,GOLD,true));c.addView(tv(h,20,NAVY,true),lp(0,5,0,0));c.addView(tv(s,13,MUTED,false),lp(0,5,0,9));Button b=button(label,true);b.setEnabled(enabled);b.setAlpha(enabled?1:.45f);b.setOnClickListener(v->action.run());c.addView(b);content.addView(c,lp(0,0,0,10));}
 private void dev(){if(!p.getBoolean("reading_"+idx,false)){hub();return;}setup("dev");content.addView(banner("♥","DEVOCIONAL",cur.reference(),"Pare, reflita e deixe a Palavra falar com você."),lp(0,0,0,14));String[] h={"1  ·  Explicação do texto","2  ·  Contexto — tempo e cultura","3  ·  Aplicação — reflexão","4  ·  Prática — como viver hoje","5  ·  Oração"};for(int i=0;i<cur.devotional.length&&i<h.length;i++){LinearLayout c=card(WHITE);c.addView(tv(h[i],16,NAVY,true));TextView body=tv(cur.devotional[i],15,TEXT,false);body.setLineSpacing(1.12f,1);c.addView(body,lp(0,8,0,0));content.addView(c,lp(0,0,0,10));}Button done=button("✓   Concluir devocional e avançar",true);done.setOnClickListener(v->complete());content.addView(done);}
 private void complete(){p.edit().putBoolean("reading_"+idx,true).putBoolean("devotional_"+idx,true).putBoolean("day_"+todayKey(),true).putInt("current_reading",idx+1).apply();idx++;cur=idx<rs.size()?rs.get(idx):null;home();}
 private String todayKey(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
 private void journey(){setup("journey");header("MINHA JORNADA","Seu caminho pela Bíblia","Acompanhe seu progresso sem perder o ritmo.");LinearLayout pc=card(NAVY);int pct=rs.size()==0?0:idx*100/rs.size();pc.addView(tv("SEU PROGRESSO",10,GOLD,true));pc.addView(serif(pct+"%",34,WHITE),lp(0,7,0,2));pc.addView(tv(idx+" etapas concluídas de "+rs.size(),13,Color.rgb(215,225,234),false));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,rs.size()));bar.setProgress(idx);pc.addView(bar,lp(0,10,0,0));content.addView(pc,lp(0,0,0,12));LinearLayout stats=new LinearLayout(this);String[] values={""+idx,""+days(),""+streak()};String[] labels={"etapas","dias lidos","sequência"};for(int i=0;i<3;i++){LinearLayout c=card(WHITE);TextView a=serif(values[i],22,GREEN);a.setGravity(Gravity.CENTER);c.addView(a);TextView z=tv(labels[i],10,MUTED,false);z.setGravity(Gravity.CENTER);c.addView(z,lp(0,5,0,0));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,-2,1);q.setMargins(i==0?0:dp(4),0,0,0);stats.addView(c,q);}content.addView(stats,lp(0,0,0,12));calendar();}
 private int days(){int n=0;for(String k:p.getAll().keySet())if(k.startsWith("day_")&&k.length()==14)n++;return n;}
 private int streak(){Calendar c=Calendar.getInstance();int n=0;while(true){String key=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime());if(!p.getBoolean("day_"+key,false))break;n++;c.add(Calendar.DAY_OF_YEAR,-1);}return n;}
 private void calendar(){LinearLayout c=card(WHITE);c.addView(tv("Calendário de leitura",19,NAVY,true));Calendar now=Calendar.getInstance();c.addView(tv(new SimpleDateFormat("MMMM yyyy",new Locale("pt","BR")).format(now.getTime()),14,MUTED,false),lp(0,5,0,8));String[] names={"D","S","T","Q","Q","S","S"};LinearLayout week=new LinearLayout(this);for(String s:names){TextView x=tv(s,10,MUTED,true);x.setGravity(Gravity.CENTER);week.addView(x,new LinearLayout.LayoutParams(0,dp(30),1));}c.addView(week);Calendar f=(Calendar)now.clone();f.set(Calendar.DAY_OF_MONTH,1);int off=f.get(Calendar.DAY_OF_WEEK)-1,max=f.getActualMaximum(Calendar.DAY_OF_MONTH);LinearLayout row=null;int col=0;for(int z=0;z<off;z++){if(col==0){row=new LinearLayout(this);c.addView(row);}row.addView(tv("",13,MUTED,false),new LinearLayout.LayoutParams(0,dp(38),1));col++;}for(int day=1;day<=max;day++){if(col==0){row=new LinearLayout(this);c.addView(row);}String key=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(date(now,day));boolean done=p.getBoolean("day_"+key,false);TextView x=tv(""+day,12,done?GREEN:MUTED,done);x.setGravity(Gravity.CENTER);x.setBackground(done?bg(GREEN_LIGHT,18):bg(Color.TRANSPARENT,18));row.addView(x,new LinearLayout.LayoutParams(0,dp(38),1));col++;if(col==7)col=0;}content.addView(c);}
 private Date date(Calendar base,int d){Calendar x=(Calendar)base.clone();x.set(Calendar.DAY_OF_MONTH,d);return x.getTime();}
 private void more(){setup("more");header("MAIS","Tudo em um só lugar","Informações e ações rápidas do aplicativo.");option("⚙","Configurações","Preferências do aplicativo",()->Toast.makeText(this,"As configurações serão ampliadas nas próximas versões.",Toast.LENGTH_SHORT).show());option("ⓘ","Sobre o aplicativo","A Jornada da Bíblia",()->about());option("?","Ajuda","Como funciona a jornada",()->help());option("↗","Compartilhar app","Convide alguém para começar a leitura",()->share());option("★","Avaliar aplicativo","Deixe sua avaliação na loja",()->rate());LinearLayout note=card(CREAM);note.addView(tv("SOBRE A JORNADA",10,GREEN,true));note.addView(tv("A proposta é caminhar pela Bíblia em sequência, mantendo a leitura e o devocional como etapas separadas.",14,TEXT,false),lp(0,7,0,0));content.addView(note,lp(0,2,0,0));}
 private void option(String icon,String title,String sub,final Runnable action){LinearLayout c=card(WHITE);LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);TextView i=tv(icon,23,GOLD,false);i.setGravity(Gravity.CENTER);line.addView(i,new LinearLayout.LayoutParams(dp(40),dp(42)));LinearLayout texts=new LinearLayout(this);texts.setOrientation(LinearLayout.VERTICAL);texts.addView(tv(title,17,NAVY,true));texts.addView(tv(sub,12,MUTED,false),lp(0,4,0,0));line.addView(texts,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=tv("›",28,MUTED,false);line.addView(arrow,new LinearLayout.LayoutParams(dp(28),dp(42)));c.addView(line);c.setOnClickListener(v->action.run());content.addView(c,lp(0,0,0,9));}
 private void about(){new AlertDialog.Builder(this).setTitle("A Jornada da Bíblia").setMessage("Uma jornada de leitura sequencial da Bíblia, com leitura na NTLH pela Sociedade Bíblica do Brasil e momentos devocionais organizados em cinco partes.\n\nVersão inicial do aplicativo de Samuel Marvila.").setPositiveButton("Fechar",null).show();}
 private void help(){new AlertDialog.Builder(this).setTitle("Como funciona").setMessage("1. Abra a Leitura do dia.\n2. Leia a passagem na NTLH.\n3. Marque a leitura como concluída.\n4. Faça o devocional: explicação, contexto, aplicação, prática e oração.\n5. Conclua o devocional.\n\nSomente então a próxima etapa é liberada. Se você passar um dia sem concluir, a etapa atual permanece aguardando você.").setPositiveButton("Entendi",null).show();}
 private void share(){Intent s=new Intent(Intent.ACTION_SEND);s.setType("text/plain");s.putExtra(Intent.EXTRA_TEXT,"Estou fazendo uma jornada de leitura da Bíblia no app A Jornada da Bíblia. Venha começar também!");startActivity(Intent.createChooser(s,"Compartilhar app"));}
 private void rate(){try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id="+getPackageName())));}catch(Exception e){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://play.google.com/store/apps/details?id="+getPackageName())));}}
}
