package br.com.samuelmarvila.ajornadadabiblia;

import android.app.*;import android.os.*;import android.content.*;import android.content.SharedPreferences;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class PremiumActivity extends Activity{
 private static final int NAVY=Color.rgb(9,29,51),NAVY2=Color.rgb(18,52,78),GOLD=Color.rgb(220,174,76),CREAM=Color.rgb(249,247,242),TEXT=Color.rgb(30,40,51),MUTED=Color.rgb(105,113,122),GREEN=Color.rgb(42,143,91),WHITE=Color.WHITE,LINE=Color.rgb(226,226,222);
 private SharedPreferences p; private List<Reading> rs; private Reading cur; private LinearLayout root,content; private CheckBox read; private int idx;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);p=getSharedPreferences("jornada",MODE_PRIVATE);rs=ReadingPlan.build();idx=p.getInt("current_reading",findLev());cur=idx<rs.size()?rs.get(idx):null;home();}
 private int findLev(){for(int i=0;i<rs.size();i++){Reading r=rs.get(i);if(r.book.equals("Levítico")&&r.chapter==1&&r.startVerse==1)return i;}return 0;}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 private TextView tv(String s,float z,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setIncludeFontPadding(false);t.setTypeface(Typeface.create("sans-serif",bold?Typeface.BOLD:Typeface.NORMAL));return t;}
 private TextView serif(String s,float z,int color){TextView t=tv(s,z,color,false);t.setTypeface(Typeface.create("serif",Typeface.NORMAL));return t;}
 private GradientDrawable shape(int color,int r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
 private GradientDrawable stroke(int fill,int sc,int r){GradientDrawable g=shape(fill,r);g.setStroke(dp(1),sc);return g;}
 private Button btn(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setMinHeight(dp(50));b.setPadding(dp(16),dp(4),dp(16),dp(4));b.setStateListAnimator(null);b.setTextColor(primary?WHITE:NAVY);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(shape(primary?GREEN:WHITE,16));return b;}
 private LinearLayout card(int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(17),dp(18),dp(17));c.setBackground(stroke(color,color==WHITE?LINE:color,22));return c;}
 private LinearLayout.LayoutParams margin(int l,int t,int r,int b){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.setMargins(l,t,r,b);return x;}
 private void setup(String selected){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CREAM);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(10),dp(16),dp(20));ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));nav(selected);setContentView(root);}
 private void nav(String selected){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(6),dp(6),dp(6),dp(8));n.setBackground(shape(NAVY,25));String[] a={"⌂\nInício","▣\nLeitura","♥\nDevocional","◷\nJornada","☰\nMais"},k={"home","read","dev","journey","more"};for(int i=0;i<a.length;i++){TextView x=tv(a[i],11,k[i].equals(selected)?GOLD:Color.rgb(191,204,216),true);x.setGravity(Gravity.CENTER);x.setLineSpacing(.8f,1);final String q=k[i];x.setOnClickListener(v->{if(q.equals("home"))home();else if(q.equals("read"))reading();else if(q.equals("dev"))hub();else if(q.equals("journey"))journey();else Toast.makeText(this,"Em breve",Toast.LENGTH_SHORT).show();});n.addView(x,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(n,new LinearLayout.LayoutParams(-1,dp(72)));}
 private void title(String eyebrow,String heading,String sub){TextView e=tv(eyebrow,10,GOLD,true);e.setLetterSpacing(.12f);content.addView(e);TextView h=serif(heading,30,NAVY);h.setTypeface(Typeface.create("serif",Typeface.BOLD));h.setPadding(0,dp(5),0,dp(4));content.addView(h);content.addView(tv(sub,14,MUTED,false),margin(0,0,0,dp(14)));}
 private void hero(String eyebrow,String heading,String sub,String reference){FrameLayout f=new FrameLayout(this);f.setBackground(shape(NAVY,28));f.setPadding(dp(20),dp(18),dp(20),dp(16));Hero art=new Hero(this);f.addView(art,new FrameLayout.LayoutParams(-1,dp(175)));LinearLayout over=new LinearLayout(this);over.setOrientation(LinearLayout.VERTICAL);TextView e=tv(eyebrow,10,GOLD,true);e.setLetterSpacing(.12f);over.addView(e);TextView h=serif(heading,27,WHITE);h.setTypeface(Typeface.create("serif",Typeface.BOLD));h.setPadding(0,dp(4),0,dp(2));over.addView(h);over.addView(tv(sub,13,Color.rgb(222,231,238),false));if(reference!=null){TextView r=tv(reference,14,WHITE,true);r.setPadding(0,dp(9),0,0);over.addView(r);}FrameLayout.LayoutParams op=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);f.addView(over,op);content.addView(f,margin(0,0,0,dp(14)));}
 private void home(){setup("home");if(cur==null){title("JORNADA CONCLUÍDA","Parabéns!","Você chegou ao fim da sua jornada bíblica.");return;}hero("A JORNADA DA BÍBLIA","Bom dia, Samuel!","Mais um passo na sua jornada com Deus.",cur.reference());LinearLayout phrase=card(Color.rgb(255,252,242));phrase.addView(tv("☀  FRASE DO DIA",10,GREEN,true));TextView q=serif("“"+phrase()+"”",19,TEXT);q.setTypeface(Typeface.create("serif",Typeface.BOLD));q.setPadding(0,dp(8),0,dp(6));phrase.addView(q);phrase.addView(tv(cur.reference(),12,MUTED,false));content.addView(phrase,margin(0,0,0,dp(14)));TextView sec=tv("SEU PRÓXIMO PASSO",10,NAVY,true);sec.setLetterSpacing(.1f);content.addView(sec,margin(dp(2),0,0,dp(8)));Button d=btn("♥   Devocional",true);d.setOnClickListener(v->hub());content.addView(d,margin(0,0,0,dp(9)));Button j=btn("◷   Minha Jornada",false);j.setOnClickListener(v->journey());content.addView(j);}
 private String phrase(){return cur.book.equals("Levítico")?"Aproxime-se de Deus com reverência e um coração inteiro.":"Leia com atenção, reflita com sinceridade e viva a Palavra.";}
 private void reading(){setup("read");title("LEITURA DO DIA","Leia a Palavra","Um capítulo de cada vez. Uma etapa de cada vez.");if(cur==null)return;hero("ETAPA "+(idx+1)+" DE "+rs.size(),cur.reference(),cur.scope(),null);LinearLayout info=card(WHITE);info.addView(tv(cur.description,15,TEXT,false));Button open=btn("📖  Abrir NTLH",true);open.setOnClickListener(v->{Intent i=new Intent(this,WebViewActivity.class);i.putExtra("url",cur.sbbUrl());i.putExtra("title",cur.reference()+" — NTLH");startActivity(i);});info.addView(open,margin(0,dp(12),0,0));content.addView(info,margin(0,0,0,dp(12)));LinearLayout mark=card(WHITE);read=new CheckBox(this);read.setText("Eu li esta leitura na NTLH");read.setTextSize(16);read.setTextColor(TEXT);read.setChecked(p.getBoolean("reading_"+idx,false));mark.addView(read);mark.addView(tv("O devocional será liberado quando você marcar a leitura como concluída.",13,MUTED,false));content.addView(mark,margin(0,0,0,dp(12)));Button go=btn("♥  Ir para o devocional",true);go.setEnabled(read.isChecked());go.setAlpha(read.isChecked()?1:.45f);read.setOnCheckedChangeListener((b,c)->{p.edit().putBoolean("reading_"+idx,c).apply();go.setEnabled(c);go.setAlpha(c?1:.45f);});go.setOnClickListener(v->hub());content.addView(go);}
 private void hub(){setup("dev");if(cur==null){title("DEVOCIONAL","Jornada concluída","Você completou todas as etapas.");return;}hero("SEU MOMENTO COM DEUS","Devocional","Primeiro a leitura. Depois, a reflexão.",cur.reference());boolean r=p.getBoolean("reading_"+idx,false),d=p.getBoolean("devotional_"+idx,false);step("01","Leitura do dia",r?"Leitura concluída.":"Comece lendo a passagem bíblica da etapa.","📖  "+(r?"Revisar leitura":"Ler a leitura"),()->reading(),true);step("02","Devocional",d?"Etapa já concluída.":r?"Agora pare, reflita, pratique e ore.":"Disponível após concluir a leitura.",r?"♥  Ver devocional":"🔒  Primeiro faça a leitura",()->dev(),r||d);LinearLayout rule=card(Color.rgb(255,252,242));rule.addView(tv("A ORDEM DA JORNADA",10,GREEN,true));rule.addView(tv("1  Leia a Bíblia\n2  Leia o devocional\n3  Conclua os dois\n4  A próxima etapa será liberada",14,TEXT,false));content.addView(rule);}
 private void step(String n,String h,String s,String b,final Runnable action,boolean enabled){LinearLayout c=card(WHITE);c.addView(tv(n,10,GOLD,true));c.addView(tv(h,20,NAVY,true));c.addView(tv(s,13,MUTED,false),margin(0,dp(5),0,dp(9)));Button x=btn(b,true);x.setEnabled(enabled);x.setAlpha(enabled?1:.45f);x.setOnClickListener(v->action.run());c.addView(x);content.addView(c,margin(0,0,0,dp(10)));}
 private void dev(){if(!p.getBoolean("reading_"+idx,false)){hub();return;}setup("dev");hero("DEVOCIONAL",cur.reference(),"Pare, reflita e deixe a Palavra falar com você.",null);String[] h={"1  ·  Explicação do texto","2  ·  Contexto — tempo e cultura","3  ·  Aplicação — reflexão","4  ·  Prática — como viver hoje","5  ·  Oração"};for(int i=0;i<cur.devotional.length;i++){LinearLayout c=card(WHITE);c.addView(tv(h[i],16,NAVY,true));TextView b=tv(cur.devotional[i],15,TEXT,false);b.setLineSpacing(1.12f,1);b.setPadding(0,dp(7),0,0);c.addView(b);content.addView(c,margin(0,0,0,dp(10)));}Button done=btn("✓  Concluir devocional e avançar",true);done.setOnClickListener(v->complete());content.addView(done,margin(0,0,0,dp(9)));content.addView(btn("Voltar",false));}
 private void complete(){p.edit().putBoolean("reading_"+idx,true).putBoolean("devotional_"+idx,true).putInt("current_reading",idx+1).apply();idx++;cur=idx<rs.size()?rs.get(idx):null;setup("home");title("ETAPA CONCLUÍDA","Muito bem!","Leitura e devocional registrados. A próxima etapa está liberada.");if(cur!=null){Button b=btn("Próxima etapa  →",true);b.setOnClickListener(v->hub());content.addView(b);}else content.addView(tv("Você concluiu toda a jornada bíblica.",17,TEXT,true));}
 private void journey(){setup("journey");title("MINHA JORNADA","Seu caminho pela Bíblia","Acompanhe seu progresso sem perder o ritmo.");LinearLayout pc=card(NAVY);int pct=rs.size()==0?0:(int)(idx*100f/rs.size());pc.addView(tv("SEU PROGRESSO",10,GOLD,true));pc.addView(serif(pct+"%",34,WHITE));pc.addView(tv(idx+" etapas concluídas de "+rs.size(),13,Color.rgb(215,225,234),false));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,rs.size()));bar.setProgress(idx);pc.addView(bar,margin(0,dp(10),0,0));content.addView(pc,margin(0,0,0,dp(12)));LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);String[] v={""+idx,""+days(),""+streak()};String[] l={"etapas","dias lidos","sequência"};for(int i=0;i<3;i++){LinearLayout c=card(WHITE);TextView a=serif(v[i],22,GREEN);a.setGravity(Gravity.CENTER);c.addView(a);TextView z=tv(l[i],10,MUTED,false);z.setGravity(Gravity.CENTER);c.addView(z);stats.addView(c,new LinearLayout.LayoutParams(0,-2,1));}content.addView(stats,margin(0,0,0,dp(12)));calendar();}
 private int days(){int n=0;for(String k:p.getAll().keySet())if(k.startsWith("day_")&&!k.startsWith("day_count_"))n++;return n;}
 private int streak(){return days();}
 private void calendar(){LinearLayout c=card(WHITE);c.addView(tv("Calendário de leitura",19,NAVY,true));Calendar now=Calendar.getInstance();c.addView(tv(new SimpleDateFormat("MMMM yyyy",new Locale("pt","BR")).format(now.getTime()),14,MUTED,false));String[] names={"D","S","T","Q","Q","S","S"};LinearLayout hr=new LinearLayout(this);for(String s:names){TextView x=tv(s,10,MUTED,true);x.setGravity(Gravity.CENTER);hr.addView(x,new LinearLayout.LayoutParams(0,dp(32),1));}c.addView(hr);Calendar f=(Calendar)now.clone();f.set(Calendar.DAY_OF_MONTH,1);int off=f.get(Calendar.DAY_OF_WEEK)-1,max=f.getActualMaximum(Calendar.DAY_OF_MONTH);LinearLayout row=null;int col=0;for(int z=0;z<off;z++){if(col==0){row=new LinearLayout(this);c.addView(row);}row.addView(tv("",13,MUTED,false),new LinearLayout.LayoutParams(0,dp(38),1));col++;}for(int day=1;day<=max;day++){if(col==0){row=new LinearLayout(this);c.addView(row);}String key=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(date(now,day));boolean done=p.getBoolean("day_"+key,false);TextView x=tv(""+day,12,done?GREEN:MUTED,done);x.setGravity(Gravity.CENTER);x.setBackground(done?shape(Color.rgb(215,239,224),18):shape(Color.TRANSPARENT,18));row.addView(x,new LinearLayout.LayoutParams(0,dp(38),1));col++;if(col==7)col=0;}content.addView(c);}
 private Date date(Calendar base,int d){Calendar x=(Calendar)base.clone();x.set(Calendar.DAY_OF_MONTH,d);return x.getTime();}
 private static class Hero extends View{Paint p=new Paint(1);Path q=new Path();Hero(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setShader(new LinearGradient(0,0,0,h,Color.rgb(40,82,111),Color.rgb(7,27,46),Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.rgb(229,179,78));c.drawCircle(w-38,34,16,p);p.setColor(Color.rgb(29,64,83));q.reset();q.moveTo(0,h*.78f);q.lineTo(w*.23f,h*.40f);q.lineTo(w*.42f,h*.76f);q.lineTo(w*.66f,h*.34f);q.lineTo(w,h*.72f);q.lineTo(w,h);q.lineTo(0,h);q.close();c.drawPath(q,p);p.setColor(Color.rgb(13,42,59));q.reset();q.moveTo(0,h*.86f);q.lineTo(w*.34f,h*.55f);q.lineTo(w*.53f,h*.82f);q.lineTo(w*.76f,h*.57f);q.lineTo(w,h*.82f);q.lineTo(w,h);q.lineTo(0,h);q.close();c.drawPath(q,p);p.setColor(Color.rgb(242,240,228));q.reset();q.moveTo(w*.36f,h*.78f);q.lineTo(w*.5f,h*.62f);q.lineTo(w*.64f,h*.78f);q.lineTo(w*.5f,h*.92f);q.close();c.drawPath(q,p);}}
}
