package br.com.samuelmarvila.ajornadadabiblia;

import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.speech.tts.*;import android.view.*;import android.webkit.*;import android.widget.*;import java.util.*;

public class WebViewActivity extends Activity{
 private WebView web;private ProgressBar progress;private String url;private TextToSpeech tts;
 private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
 @Override public void onCreate(Bundle state){super.onCreate(state);url=getIntent().getStringExtra("url");if(url==null)url="https://www.sbb.org.br/biblia/NTLH/LEV.1";LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(10),dp(12),0);root.setBackgroundColor(Color.rgb(246,247,245));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=new TextView(this);title.setText("NTLH");title.setTextSize(20);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setTextColor(Color.rgb(22,75,59));top.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));Button voice=new Button(this);voice.setText("Ouvir");voice.setAllCaps(false);voice.setTextSize(13);voice.setMinHeight(dp(44));voice.setOnClickListener(v->speakPage());top.addView(voice,new LinearLayout.LayoutParams(dp(86),dp(48)));Button browser=new Button(this);browser.setText("Abrir fora");browser.setAllCaps(false);browser.setTextSize(13);browser.setMinHeight(dp(44));browser.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url))));top.addView(browser,new LinearLayout.LayoutParams(dp(100),dp(48)));root.addView(top);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setVisibility(ProgressBar.INVISIBLE);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);s.setLoadWithOverviewMode(true);s.setUseWideViewPort(true);web.setBackgroundColor(Color.WHITE);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri target=r.getUrl();if(target.getHost()!=null&&target.getHost().endsWith("sbb.org.br"))return false;startActivity(new Intent(Intent.ACTION_VIEW,target));return true;}@Override public void onPageStarted(WebView v,String u,android.graphics.Bitmap f){progress.setVisibility(ProgressBar.VISIBLE);}@Override public void onPageFinished(WebView v,String u){progress.setProgress(100);progress.setVisibility(ProgressBar.INVISIBLE);}});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);tts=new TextToSpeech(this,s->{if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("pt","BR"));tts.setSpeechRate(.9f);}});web.loadUrl(url);}
 private void speakPage(){if(tts==null||web==null)return;web.evaluateJavascript("(function(){var e=document.querySelector('main,article,[role=main]');return JSON.stringify((e||document.body).innerText);})()",value->{String text=value;if(text!=null){text=text.replaceAll("^\\\"|\\\"$","").replaceAll("\\\\n"," ").replaceAll("\\\\\"","\\\"");if(text.length()>12000)text=text.substring(0,12000);tts.stop();tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"bible-reading");Toast.makeText(this,"Leitura em voz alta iniciada",Toast.LENGTH_SHORT).show();}});}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack()){web.goBack();}else{finish();}}
 @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}if(web!=null)web.destroy();super.onDestroy();}
}
